/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTransferData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaTransferData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTransferData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTransferData(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaTransferData copy() {
    long cPtr = megaJNI.MegaTransferData_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTransferData(cPtr, false);
  }

  public int getNumDownloads() {
    return megaJNI.MegaTransferData_getNumDownloads(swigCPtr, this);
  }

  public int getNumUploads() {
    return megaJNI.MegaTransferData_getNumUploads(swigCPtr, this);
  }

  public int getDownloadTag(int i) {
    return megaJNI.MegaTransferData_getDownloadTag(swigCPtr, this, i);
  }

  public int getUploadTag(int i) {
    return megaJNI.MegaTransferData_getUploadTag(swigCPtr, this, i);
  }

  public java.math.BigInteger getDownloadPriority(int i) {
    return megaJNI.MegaTransferData_getDownloadPriority(swigCPtr, this, i);
  }

  public java.math.BigInteger getUploadPriority(int i) {
    return megaJNI.MegaTransferData_getUploadPriority(swigCPtr, this, i);
  }

  public long getNotificationNumber() {
    return megaJNI.MegaTransferData_getNotificationNumber(swigCPtr, this);
  }

  public MegaTransferData() {
    this(megaJNI.new_MegaTransferData(), true);
  }

}
