/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaStringMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaStringMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaStringMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaStringMap(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaStringMap copy() {
    long cPtr = megaJNI.MegaStringMap_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringMap(cPtr, false);
  }

  public String get(String key) {
    return megaJNI.MegaStringMap_get(swigCPtr, this, key);
  }

  public MegaStringList getKeys() {
    long cPtr = megaJNI.MegaStringMap_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public void set(String key, String value) {
    megaJNI.MegaStringMap_set(swigCPtr, this, key, value);
  }

  public int size() {
    return megaJNI.MegaStringMap_size(swigCPtr, this);
  }

  public MegaStringMap() {
    this(megaJNI.new_MegaStringMap(), true);
  }

}
