/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaEvent copy() {
    long cPtr = megaJNI.MegaEvent_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaEvent(cPtr, false);
  }

  public int getType() {
    return megaJNI.MegaEvent_getType(swigCPtr, this);
  }

  public String getText() {
    return megaJNI.MegaEvent_getText(swigCPtr, this);
  }

  public MegaEvent() {
    this(megaJNI.new_MegaEvent(), true);
  }

  public final static int EVENT_COMMIT_DB = 0;
  public final static int EVENT_ACCOUNT_CONFIRMATION = 1;

}
